import type { GeneratorPlugin } from '@open-mercato/shared/modules/generators'

function buildOutput({ importSection, entriesLiteral }: { importSection: string; entriesLiteral: string }): string {
  return `// AUTO-GENERATED by mercato generate registry — do not edit manually
// Run \`yarn generate\` to regenerate after adding activity-types.ts to a module

import type { ActivityTypeDefinition } from '@app/modules/activities/activity-types'
${importSection ? `${importSection}\n` : ''}
const _registry: ActivityTypeDefinition[] = [
${entriesLiteral ? `  ${entriesLiteral}\n` : ''}]

export function getActivityType(id: string): ActivityTypeDefinition | undefined {
  return _registry.find((t) => t.id === id)
}

export function getAllActivityTypes(): ActivityTypeDefinition[] {
  return _registry
}

export function getActivityTypesByModule(moduleId: string): ActivityTypeDefinition[] {
  return _registry.filter((t) => t.moduleId === moduleId)
}
`
}

export const generatorPlugins: GeneratorPlugin[] = [
  {
    id: 'activities.type-registry',
    conventionFile: 'activity-types.ts',
    importPrefix: 'ACTIVITY_TYPES',
    configExpr: (importName: string) =>
      `...(${importName}.activityTypes ?? ${importName}.default ?? [])`,
    outputFileName: 'activity-types.generated.ts',
    buildOutput,
  },
]
